/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.additive_expression_complement;
import org.xtext.example.mydsl.myDsl.additive_expression_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>additive expression linha</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.additive_expression_linhaImpl#getAdditive_expression_complement <em>Additive expression complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.additive_expression_linhaImpl#getAdditive_expression_linha <em>Additive expression linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class additive_expression_linhaImpl extends MinimalEObjectImpl.Container implements additive_expression_linha
{
  /**
   * The cached value of the '{@link #getAdditive_expression_complement() <em>Additive expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditive_expression_complement()
   * @generated
   * @ordered
   */
  protected additive_expression_complement additive_expression_complement;

  /**
   * The cached value of the '{@link #getAdditive_expression_linha() <em>Additive expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditive_expression_linha()
   * @generated
   * @ordered
   */
  protected additive_expression_linha additive_expression_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected additive_expression_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ADDITIVE_EXPRESSION_LINHA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public additive_expression_complement getAdditive_expression_complement()
  {
    return additive_expression_complement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdditive_expression_complement(additive_expression_complement newAdditive_expression_complement, NotificationChain msgs)
  {
    additive_expression_complement oldAdditive_expression_complement = additive_expression_complement;
    additive_expression_complement = newAdditive_expression_complement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT, oldAdditive_expression_complement, newAdditive_expression_complement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdditive_expression_complement(additive_expression_complement newAdditive_expression_complement)
  {
    if (newAdditive_expression_complement != additive_expression_complement)
    {
      NotificationChain msgs = null;
      if (additive_expression_complement != null)
        msgs = ((InternalEObject)additive_expression_complement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT, null, msgs);
      if (newAdditive_expression_complement != null)
        msgs = ((InternalEObject)newAdditive_expression_complement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT, null, msgs);
      msgs = basicSetAdditive_expression_complement(newAdditive_expression_complement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT, newAdditive_expression_complement, newAdditive_expression_complement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public additive_expression_linha getAdditive_expression_linha()
  {
    return additive_expression_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdditive_expression_linha(additive_expression_linha newAdditive_expression_linha, NotificationChain msgs)
  {
    additive_expression_linha oldAdditive_expression_linha = additive_expression_linha;
    additive_expression_linha = newAdditive_expression_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA, oldAdditive_expression_linha, newAdditive_expression_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAdditive_expression_linha(additive_expression_linha newAdditive_expression_linha)
  {
    if (newAdditive_expression_linha != additive_expression_linha)
    {
      NotificationChain msgs = null;
      if (additive_expression_linha != null)
        msgs = ((InternalEObject)additive_expression_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA, null, msgs);
      if (newAdditive_expression_linha != null)
        msgs = ((InternalEObject)newAdditive_expression_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA, null, msgs);
      msgs = basicSetAdditive_expression_linha(newAdditive_expression_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA, newAdditive_expression_linha, newAdditive_expression_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT:
        return basicSetAdditive_expression_complement(null, msgs);
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA:
        return basicSetAdditive_expression_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT:
        return getAdditive_expression_complement();
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA:
        return getAdditive_expression_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT:
        setAdditive_expression_complement((additive_expression_complement)newValue);
        return;
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA:
        setAdditive_expression_linha((additive_expression_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT:
        setAdditive_expression_complement((additive_expression_complement)null);
        return;
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA:
        setAdditive_expression_linha((additive_expression_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_COMPLEMENT:
        return additive_expression_complement != null;
      case MyDslPackage.ADDITIVE_EXPRESSION_LINHA__ADDITIVE_EXPRESSION_LINHA:
        return additive_expression_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //additive_expression_linhaImpl
