/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.argument_expression_list;
import org.xtext.example.mydsl.myDsl.assignment_expression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>argument expression list</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.argument_expression_listImpl#getAssignment_expressions <em>Assignment expressions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class argument_expression_listImpl extends MinimalEObjectImpl.Container implements argument_expression_list
{
  /**
   * The cached value of the '{@link #getAssignment_expressions() <em>Assignment expressions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAssignment_expressions()
   * @generated
   * @ordered
   */
  protected EList<assignment_expression> assignment_expressions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected argument_expression_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ARGUMENT_EXPRESSION_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<assignment_expression> getAssignment_expressions()
  {
    if (assignment_expressions == null)
    {
      assignment_expressions = new EObjectContainmentEList<assignment_expression>(assignment_expression.class, this, MyDslPackage.ARGUMENT_EXPRESSION_LIST__ASSIGNMENT_EXPRESSIONS);
    }
    return assignment_expressions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT_EXPRESSION_LIST__ASSIGNMENT_EXPRESSIONS:
        return ((InternalEList<?>)getAssignment_expressions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT_EXPRESSION_LIST__ASSIGNMENT_EXPRESSIONS:
        return getAssignment_expressions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT_EXPRESSION_LIST__ASSIGNMENT_EXPRESSIONS:
        getAssignment_expressions().clear();
        getAssignment_expressions().addAll((Collection<? extends assignment_expression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT_EXPRESSION_LIST__ASSIGNMENT_EXPRESSIONS:
        getAssignment_expressions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ARGUMENT_EXPRESSION_LIST__ASSIGNMENT_EXPRESSIONS:
        return assignment_expressions != null && !assignment_expressions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //argument_expression_listImpl
