/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.declaration_list_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>declaration list linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class declaration_list_linhaImpl extends MinimalEObjectImpl.Container implements declaration_list_linha
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected declaration_list_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DECLARATION_LIST_LINHA;
  }

} //declaration_list_linhaImpl
