/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.DesignatorListLinhaAction;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.declaration_list_linha;
import org.xtext.example.mydsl.myDsl.designator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Designator List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.DesignatorListLinhaActionImpl#getDesignator <em>Designator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.DesignatorListLinhaActionImpl#getDesignator_list_linha <em>Designator list linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DesignatorListLinhaActionImpl extends designator_list_linhaImpl implements DesignatorListLinhaAction
{
  /**
   * The cached value of the '{@link #getDesignator() <em>Designator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesignator()
   * @generated
   * @ordered
   */
  protected designator designator;

  /**
   * The cached value of the '{@link #getDesignator_list_linha() <em>Designator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesignator_list_linha()
   * @generated
   * @ordered
   */
  protected declaration_list_linha designator_list_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DesignatorListLinhaActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DESIGNATOR_LIST_LINHA_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public designator getDesignator()
  {
    return designator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDesignator(designator newDesignator, NotificationChain msgs)
  {
    designator oldDesignator = designator;
    designator = newDesignator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR, oldDesignator, newDesignator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDesignator(designator newDesignator)
  {
    if (newDesignator != designator)
    {
      NotificationChain msgs = null;
      if (designator != null)
        msgs = ((InternalEObject)designator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR, null, msgs);
      if (newDesignator != null)
        msgs = ((InternalEObject)newDesignator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR, null, msgs);
      msgs = basicSetDesignator(newDesignator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR, newDesignator, newDesignator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public declaration_list_linha getDesignator_list_linha()
  {
    return designator_list_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDesignator_list_linha(declaration_list_linha newDesignator_list_linha, NotificationChain msgs)
  {
    declaration_list_linha oldDesignator_list_linha = designator_list_linha;
    designator_list_linha = newDesignator_list_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA, oldDesignator_list_linha, newDesignator_list_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDesignator_list_linha(declaration_list_linha newDesignator_list_linha)
  {
    if (newDesignator_list_linha != designator_list_linha)
    {
      NotificationChain msgs = null;
      if (designator_list_linha != null)
        msgs = ((InternalEObject)designator_list_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA, null, msgs);
      if (newDesignator_list_linha != null)
        msgs = ((InternalEObject)newDesignator_list_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA, null, msgs);
      msgs = basicSetDesignator_list_linha(newDesignator_list_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA, newDesignator_list_linha, newDesignator_list_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR:
        return basicSetDesignator(null, msgs);
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA:
        return basicSetDesignator_list_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR:
        return getDesignator();
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA:
        return getDesignator_list_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR:
        setDesignator((designator)newValue);
        return;
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA:
        setDesignator_list_linha((declaration_list_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR:
        setDesignator((designator)null);
        return;
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA:
        setDesignator_list_linha((declaration_list_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR:
        return designator != null;
      case MyDslPackage.DESIGNATOR_LIST_LINHA_ACTION__DESIGNATOR_LIST_LINHA:
        return designator_list_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //DesignatorListLinhaActionImpl
