/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.DirectAbstractDeclarratorLinhaAction;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.direct_abstract_declarator_complement;
import org.xtext.example.mydsl.myDsl.direct_abstract_declarator_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Direct Abstract Declarrator Linha Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.DirectAbstractDeclarratorLinhaActionImpl#getDirect_abstract_declarator_complement <em>Direct abstract declarator complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.DirectAbstractDeclarratorLinhaActionImpl#getDirect_abstract_declarator_linha <em>Direct abstract declarator linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DirectAbstractDeclarratorLinhaActionImpl extends direct_abstract_declarator_linhaImpl implements DirectAbstractDeclarratorLinhaAction
{
  /**
   * The cached value of the '{@link #getDirect_abstract_declarator_complement() <em>Direct abstract declarator complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirect_abstract_declarator_complement()
   * @generated
   * @ordered
   */
  protected direct_abstract_declarator_complement direct_abstract_declarator_complement;

  /**
   * The cached value of the '{@link #getDirect_abstract_declarator_linha() <em>Direct abstract declarator linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDirect_abstract_declarator_linha()
   * @generated
   * @ordered
   */
  protected direct_abstract_declarator_linha direct_abstract_declarator_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DirectAbstractDeclarratorLinhaActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public direct_abstract_declarator_complement getDirect_abstract_declarator_complement()
  {
    return direct_abstract_declarator_complement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDirect_abstract_declarator_complement(direct_abstract_declarator_complement newDirect_abstract_declarator_complement, NotificationChain msgs)
  {
    direct_abstract_declarator_complement oldDirect_abstract_declarator_complement = direct_abstract_declarator_complement;
    direct_abstract_declarator_complement = newDirect_abstract_declarator_complement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT, oldDirect_abstract_declarator_complement, newDirect_abstract_declarator_complement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDirect_abstract_declarator_complement(direct_abstract_declarator_complement newDirect_abstract_declarator_complement)
  {
    if (newDirect_abstract_declarator_complement != direct_abstract_declarator_complement)
    {
      NotificationChain msgs = null;
      if (direct_abstract_declarator_complement != null)
        msgs = ((InternalEObject)direct_abstract_declarator_complement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT, null, msgs);
      if (newDirect_abstract_declarator_complement != null)
        msgs = ((InternalEObject)newDirect_abstract_declarator_complement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT, null, msgs);
      msgs = basicSetDirect_abstract_declarator_complement(newDirect_abstract_declarator_complement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT, newDirect_abstract_declarator_complement, newDirect_abstract_declarator_complement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public direct_abstract_declarator_linha getDirect_abstract_declarator_linha()
  {
    return direct_abstract_declarator_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDirect_abstract_declarator_linha(direct_abstract_declarator_linha newDirect_abstract_declarator_linha, NotificationChain msgs)
  {
    direct_abstract_declarator_linha oldDirect_abstract_declarator_linha = direct_abstract_declarator_linha;
    direct_abstract_declarator_linha = newDirect_abstract_declarator_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA, oldDirect_abstract_declarator_linha, newDirect_abstract_declarator_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDirect_abstract_declarator_linha(direct_abstract_declarator_linha newDirect_abstract_declarator_linha)
  {
    if (newDirect_abstract_declarator_linha != direct_abstract_declarator_linha)
    {
      NotificationChain msgs = null;
      if (direct_abstract_declarator_linha != null)
        msgs = ((InternalEObject)direct_abstract_declarator_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA, null, msgs);
      if (newDirect_abstract_declarator_linha != null)
        msgs = ((InternalEObject)newDirect_abstract_declarator_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA, null, msgs);
      msgs = basicSetDirect_abstract_declarator_linha(newDirect_abstract_declarator_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA, newDirect_abstract_declarator_linha, newDirect_abstract_declarator_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT:
        return basicSetDirect_abstract_declarator_complement(null, msgs);
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA:
        return basicSetDirect_abstract_declarator_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT:
        return getDirect_abstract_declarator_complement();
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA:
        return getDirect_abstract_declarator_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT:
        setDirect_abstract_declarator_complement((direct_abstract_declarator_complement)newValue);
        return;
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA:
        setDirect_abstract_declarator_linha((direct_abstract_declarator_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT:
        setDirect_abstract_declarator_complement((direct_abstract_declarator_complement)null);
        return;
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA:
        setDirect_abstract_declarator_linha((direct_abstract_declarator_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_COMPLEMENT:
        return direct_abstract_declarator_complement != null;
      case MyDslPackage.DIRECT_ABSTRACT_DECLARRATOR_LINHA_ACTION__DIRECT_ABSTRACT_DECLARATOR_LINHA:
        return direct_abstract_declarator_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //DirectAbstractDeclarratorLinhaActionImpl
