/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.EnumeratorListLinhaAction;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.enumerator;
import org.xtext.example.mydsl.myDsl.enumerator_list_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enumerator List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EnumeratorListLinhaActionImpl#getEnumerator <em>Enumerator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.EnumeratorListLinhaActionImpl#getEnumerator_list_linha <em>Enumerator list linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumeratorListLinhaActionImpl extends enumerator_list_linhaImpl implements EnumeratorListLinhaAction
{
  /**
   * The cached value of the '{@link #getEnumerator() <em>Enumerator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerator()
   * @generated
   * @ordered
   */
  protected enumerator enumerator;

  /**
   * The cached value of the '{@link #getEnumerator_list_linha() <em>Enumerator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerator_list_linha()
   * @generated
   * @ordered
   */
  protected enumerator_list_linha enumerator_list_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumeratorListLinhaActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ENUMERATOR_LIST_LINHA_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public enumerator getEnumerator()
  {
    return enumerator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumerator(enumerator newEnumerator, NotificationChain msgs)
  {
    enumerator oldEnumerator = enumerator;
    enumerator = newEnumerator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR, oldEnumerator, newEnumerator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnumerator(enumerator newEnumerator)
  {
    if (newEnumerator != enumerator)
    {
      NotificationChain msgs = null;
      if (enumerator != null)
        msgs = ((InternalEObject)enumerator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR, null, msgs);
      if (newEnumerator != null)
        msgs = ((InternalEObject)newEnumerator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR, null, msgs);
      msgs = basicSetEnumerator(newEnumerator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR, newEnumerator, newEnumerator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public enumerator_list_linha getEnumerator_list_linha()
  {
    return enumerator_list_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumerator_list_linha(enumerator_list_linha newEnumerator_list_linha, NotificationChain msgs)
  {
    enumerator_list_linha oldEnumerator_list_linha = enumerator_list_linha;
    enumerator_list_linha = newEnumerator_list_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA, oldEnumerator_list_linha, newEnumerator_list_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnumerator_list_linha(enumerator_list_linha newEnumerator_list_linha)
  {
    if (newEnumerator_list_linha != enumerator_list_linha)
    {
      NotificationChain msgs = null;
      if (enumerator_list_linha != null)
        msgs = ((InternalEObject)enumerator_list_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA, null, msgs);
      if (newEnumerator_list_linha != null)
        msgs = ((InternalEObject)newEnumerator_list_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA, null, msgs);
      msgs = basicSetEnumerator_list_linha(newEnumerator_list_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA, newEnumerator_list_linha, newEnumerator_list_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR:
        return basicSetEnumerator(null, msgs);
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA:
        return basicSetEnumerator_list_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR:
        return getEnumerator();
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA:
        return getEnumerator_list_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR:
        setEnumerator((enumerator)newValue);
        return;
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA:
        setEnumerator_list_linha((enumerator_list_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR:
        setEnumerator((enumerator)null);
        return;
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA:
        setEnumerator_list_linha((enumerator_list_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR:
        return enumerator != null;
      case MyDslPackage.ENUMERATOR_LIST_LINHA_ACTION__ENUMERATOR_LIST_LINHA:
        return enumerator_list_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //EnumeratorListLinhaActionImpl
