/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.enumerator;
import org.xtext.example.mydsl.myDsl.enumerator_list;
import org.xtext.example.mydsl.myDsl.enumerator_list_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>enumerator list</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.enumerator_listImpl#getEnumarator <em>Enumarator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.enumerator_listImpl#getEnumerator_list_linha <em>Enumerator list linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class enumerator_listImpl extends MinimalEObjectImpl.Container implements enumerator_list
{
  /**
   * The cached value of the '{@link #getEnumarator() <em>Enumarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumarator()
   * @generated
   * @ordered
   */
  protected enumerator enumarator;

  /**
   * The cached value of the '{@link #getEnumerator_list_linha() <em>Enumerator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerator_list_linha()
   * @generated
   * @ordered
   */
  protected enumerator_list_linha enumerator_list_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected enumerator_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ENUMERATOR_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public enumerator getEnumarator()
  {
    return enumarator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumarator(enumerator newEnumarator, NotificationChain msgs)
  {
    enumerator oldEnumarator = enumarator;
    enumarator = newEnumarator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST__ENUMARATOR, oldEnumarator, newEnumarator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnumarator(enumerator newEnumarator)
  {
    if (newEnumarator != enumarator)
    {
      NotificationChain msgs = null;
      if (enumarator != null)
        msgs = ((InternalEObject)enumarator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST__ENUMARATOR, null, msgs);
      if (newEnumarator != null)
        msgs = ((InternalEObject)newEnumarator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST__ENUMARATOR, null, msgs);
      msgs = basicSetEnumarator(newEnumarator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST__ENUMARATOR, newEnumarator, newEnumarator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public enumerator_list_linha getEnumerator_list_linha()
  {
    return enumerator_list_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnumerator_list_linha(enumerator_list_linha newEnumerator_list_linha, NotificationChain msgs)
  {
    enumerator_list_linha oldEnumerator_list_linha = enumerator_list_linha;
    enumerator_list_linha = newEnumerator_list_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA, oldEnumerator_list_linha, newEnumerator_list_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnumerator_list_linha(enumerator_list_linha newEnumerator_list_linha)
  {
    if (newEnumerator_list_linha != enumerator_list_linha)
    {
      NotificationChain msgs = null;
      if (enumerator_list_linha != null)
        msgs = ((InternalEObject)enumerator_list_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA, null, msgs);
      if (newEnumerator_list_linha != null)
        msgs = ((InternalEObject)newEnumerator_list_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA, null, msgs);
      msgs = basicSetEnumerator_list_linha(newEnumerator_list_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA, newEnumerator_list_linha, newEnumerator_list_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST__ENUMARATOR:
        return basicSetEnumarator(null, msgs);
      case MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA:
        return basicSetEnumerator_list_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST__ENUMARATOR:
        return getEnumarator();
      case MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA:
        return getEnumerator_list_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST__ENUMARATOR:
        setEnumarator((enumerator)newValue);
        return;
      case MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA:
        setEnumerator_list_linha((enumerator_list_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST__ENUMARATOR:
        setEnumarator((enumerator)null);
        return;
      case MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA:
        setEnumerator_list_linha((enumerator_list_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ENUMERATOR_LIST__ENUMARATOR:
        return enumarator != null;
      case MyDslPackage.ENUMERATOR_LIST__ENUMERATOR_LIST_LINHA:
        return enumerator_list_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //enumerator_listImpl
