/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.GenericAssocListLinhaAction;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.generic_assoc_list_linha;
import org.xtext.example.mydsl.myDsl.generic_association;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Generic Assoc List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GenericAssocListLinhaActionImpl#getGeneric_association <em>Generic association</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GenericAssocListLinhaActionImpl#getGeneric_assoc_list_linha <em>Generic assoc list linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GenericAssocListLinhaActionImpl extends generic_assoc_list_linhaImpl implements GenericAssocListLinhaAction
{
  /**
   * The cached value of the '{@link #getGeneric_association() <em>Generic association</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGeneric_association()
   * @generated
   * @ordered
   */
  protected generic_association generic_association;

  /**
   * The cached value of the '{@link #getGeneric_assoc_list_linha() <em>Generic assoc list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGeneric_assoc_list_linha()
   * @generated
   * @ordered
   */
  protected generic_assoc_list_linha generic_assoc_list_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GenericAssocListLinhaActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.GENERIC_ASSOC_LIST_LINHA_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public generic_association getGeneric_association()
  {
    return generic_association;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGeneric_association(generic_association newGeneric_association, NotificationChain msgs)
  {
    generic_association oldGeneric_association = generic_association;
    generic_association = newGeneric_association;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION, oldGeneric_association, newGeneric_association);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGeneric_association(generic_association newGeneric_association)
  {
    if (newGeneric_association != generic_association)
    {
      NotificationChain msgs = null;
      if (generic_association != null)
        msgs = ((InternalEObject)generic_association).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION, null, msgs);
      if (newGeneric_association != null)
        msgs = ((InternalEObject)newGeneric_association).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION, null, msgs);
      msgs = basicSetGeneric_association(newGeneric_association, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION, newGeneric_association, newGeneric_association));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public generic_assoc_list_linha getGeneric_assoc_list_linha()
  {
    return generic_assoc_list_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGeneric_assoc_list_linha(generic_assoc_list_linha newGeneric_assoc_list_linha, NotificationChain msgs)
  {
    generic_assoc_list_linha oldGeneric_assoc_list_linha = generic_assoc_list_linha;
    generic_assoc_list_linha = newGeneric_assoc_list_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA, oldGeneric_assoc_list_linha, newGeneric_assoc_list_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGeneric_assoc_list_linha(generic_assoc_list_linha newGeneric_assoc_list_linha)
  {
    if (newGeneric_assoc_list_linha != generic_assoc_list_linha)
    {
      NotificationChain msgs = null;
      if (generic_assoc_list_linha != null)
        msgs = ((InternalEObject)generic_assoc_list_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA, null, msgs);
      if (newGeneric_assoc_list_linha != null)
        msgs = ((InternalEObject)newGeneric_assoc_list_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA, null, msgs);
      msgs = basicSetGeneric_assoc_list_linha(newGeneric_assoc_list_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA, newGeneric_assoc_list_linha, newGeneric_assoc_list_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION:
        return basicSetGeneric_association(null, msgs);
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA:
        return basicSetGeneric_assoc_list_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION:
        return getGeneric_association();
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA:
        return getGeneric_assoc_list_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION:
        setGeneric_association((generic_association)newValue);
        return;
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA:
        setGeneric_assoc_list_linha((generic_assoc_list_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION:
        setGeneric_association((generic_association)null);
        return;
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA:
        setGeneric_assoc_list_linha((generic_assoc_list_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOCIATION:
        return generic_association != null;
      case MyDslPackage.GENERIC_ASSOC_LIST_LINHA_ACTION__GENERIC_ASSOC_LIST_LINHA:
        return generic_assoc_list_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //GenericAssocListLinhaActionImpl
