/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.InitializerListLinhaAction;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.init_declarator_list_linha;
import org.xtext.example.mydsl.myDsl.initializer_list_complement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initializer List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.InitializerListLinhaActionImpl#getInitializer_list_complement <em>Initializer list complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.InitializerListLinhaActionImpl#getInit_declarator_list_linha <em>Init declarator list linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitializerListLinhaActionImpl extends initializer_list_linhaImpl implements InitializerListLinhaAction
{
  /**
   * The cached value of the '{@link #getInitializer_list_complement() <em>Initializer list complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitializer_list_complement()
   * @generated
   * @ordered
   */
  protected initializer_list_complement initializer_list_complement;

  /**
   * The cached value of the '{@link #getInit_declarator_list_linha() <em>Init declarator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_declarator_list_linha()
   * @generated
   * @ordered
   */
  protected init_declarator_list_linha init_declarator_list_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitializerListLinhaActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INITIALIZER_LIST_LINHA_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public initializer_list_complement getInitializer_list_complement()
  {
    return initializer_list_complement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitializer_list_complement(initializer_list_complement newInitializer_list_complement, NotificationChain msgs)
  {
    initializer_list_complement oldInitializer_list_complement = initializer_list_complement;
    initializer_list_complement = newInitializer_list_complement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT, oldInitializer_list_complement, newInitializer_list_complement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInitializer_list_complement(initializer_list_complement newInitializer_list_complement)
  {
    if (newInitializer_list_complement != initializer_list_complement)
    {
      NotificationChain msgs = null;
      if (initializer_list_complement != null)
        msgs = ((InternalEObject)initializer_list_complement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT, null, msgs);
      if (newInitializer_list_complement != null)
        msgs = ((InternalEObject)newInitializer_list_complement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT, null, msgs);
      msgs = basicSetInitializer_list_complement(newInitializer_list_complement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT, newInitializer_list_complement, newInitializer_list_complement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public init_declarator_list_linha getInit_declarator_list_linha()
  {
    return init_declarator_list_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit_declarator_list_linha(init_declarator_list_linha newInit_declarator_list_linha, NotificationChain msgs)
  {
    init_declarator_list_linha oldInit_declarator_list_linha = init_declarator_list_linha;
    init_declarator_list_linha = newInit_declarator_list_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA, oldInit_declarator_list_linha, newInit_declarator_list_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInit_declarator_list_linha(init_declarator_list_linha newInit_declarator_list_linha)
  {
    if (newInit_declarator_list_linha != init_declarator_list_linha)
    {
      NotificationChain msgs = null;
      if (init_declarator_list_linha != null)
        msgs = ((InternalEObject)init_declarator_list_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA, null, msgs);
      if (newInit_declarator_list_linha != null)
        msgs = ((InternalEObject)newInit_declarator_list_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA, null, msgs);
      msgs = basicSetInit_declarator_list_linha(newInit_declarator_list_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA, newInit_declarator_list_linha, newInit_declarator_list_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT:
        return basicSetInitializer_list_complement(null, msgs);
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA:
        return basicSetInit_declarator_list_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT:
        return getInitializer_list_complement();
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA:
        return getInit_declarator_list_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT:
        setInitializer_list_complement((initializer_list_complement)newValue);
        return;
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA:
        setInit_declarator_list_linha((init_declarator_list_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT:
        setInitializer_list_complement((initializer_list_complement)null);
        return;
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA:
        setInit_declarator_list_linha((init_declarator_list_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INITIALIZER_LIST_COMPLEMENT:
        return initializer_list_complement != null;
      case MyDslPackage.INITIALIZER_LIST_LINHA_ACTION__INIT_DECLARATOR_LIST_LINHA:
        return init_declarator_list_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //InitializerListLinhaActionImpl
