/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.multiplicative_expression_complement;
import org.xtext.example.mydsl.myDsl.multiplicative_expression_linha;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>multiplicative expression linha</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.multiplicative_expression_linhaImpl#getMultiplicative_expression_complement <em>Multiplicative expression complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.multiplicative_expression_linhaImpl#getMultiplicative_expression_linha <em>Multiplicative expression linha</em>}</li>
 * </ul>
 *
 * @generated
 */
public class multiplicative_expression_linhaImpl extends MinimalEObjectImpl.Container implements multiplicative_expression_linha
{
  /**
   * The cached value of the '{@link #getMultiplicative_expression_complement() <em>Multiplicative expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiplicative_expression_complement()
   * @generated
   * @ordered
   */
  protected multiplicative_expression_complement multiplicative_expression_complement;

  /**
   * The cached value of the '{@link #getMultiplicative_expression_linha() <em>Multiplicative expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMultiplicative_expression_linha()
   * @generated
   * @ordered
   */
  protected multiplicative_expression_linha multiplicative_expression_linha;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected multiplicative_expression_linhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MULTIPLICATIVE_EXPRESSION_LINHA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public multiplicative_expression_complement getMultiplicative_expression_complement()
  {
    return multiplicative_expression_complement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMultiplicative_expression_complement(multiplicative_expression_complement newMultiplicative_expression_complement, NotificationChain msgs)
  {
    multiplicative_expression_complement oldMultiplicative_expression_complement = multiplicative_expression_complement;
    multiplicative_expression_complement = newMultiplicative_expression_complement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT, oldMultiplicative_expression_complement, newMultiplicative_expression_complement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMultiplicative_expression_complement(multiplicative_expression_complement newMultiplicative_expression_complement)
  {
    if (newMultiplicative_expression_complement != multiplicative_expression_complement)
    {
      NotificationChain msgs = null;
      if (multiplicative_expression_complement != null)
        msgs = ((InternalEObject)multiplicative_expression_complement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT, null, msgs);
      if (newMultiplicative_expression_complement != null)
        msgs = ((InternalEObject)newMultiplicative_expression_complement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT, null, msgs);
      msgs = basicSetMultiplicative_expression_complement(newMultiplicative_expression_complement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT, newMultiplicative_expression_complement, newMultiplicative_expression_complement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public multiplicative_expression_linha getMultiplicative_expression_linha()
  {
    return multiplicative_expression_linha;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMultiplicative_expression_linha(multiplicative_expression_linha newMultiplicative_expression_linha, NotificationChain msgs)
  {
    multiplicative_expression_linha oldMultiplicative_expression_linha = multiplicative_expression_linha;
    multiplicative_expression_linha = newMultiplicative_expression_linha;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA, oldMultiplicative_expression_linha, newMultiplicative_expression_linha);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMultiplicative_expression_linha(multiplicative_expression_linha newMultiplicative_expression_linha)
  {
    if (newMultiplicative_expression_linha != multiplicative_expression_linha)
    {
      NotificationChain msgs = null;
      if (multiplicative_expression_linha != null)
        msgs = ((InternalEObject)multiplicative_expression_linha).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA, null, msgs);
      if (newMultiplicative_expression_linha != null)
        msgs = ((InternalEObject)newMultiplicative_expression_linha).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA, null, msgs);
      msgs = basicSetMultiplicative_expression_linha(newMultiplicative_expression_linha, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA, newMultiplicative_expression_linha, newMultiplicative_expression_linha));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT:
        return basicSetMultiplicative_expression_complement(null, msgs);
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA:
        return basicSetMultiplicative_expression_linha(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT:
        return getMultiplicative_expression_complement();
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA:
        return getMultiplicative_expression_linha();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT:
        setMultiplicative_expression_complement((multiplicative_expression_complement)newValue);
        return;
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA:
        setMultiplicative_expression_linha((multiplicative_expression_linha)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT:
        setMultiplicative_expression_complement((multiplicative_expression_complement)null);
        return;
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA:
        setMultiplicative_expression_linha((multiplicative_expression_linha)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_COMPLEMENT:
        return multiplicative_expression_complement != null;
      case MyDslPackage.MULTIPLICATIVE_EXPRESSION_LINHA__MULTIPLICATIVE_EXPRESSION_LINHA:
        return multiplicative_expression_linha != null;
    }
    return super.eIsSet(featureID);
  }

} //multiplicative_expression_linhaImpl
