/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.parameter_lista;
import org.xtext.example.mydsl.myDsl.parameter_type_list;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>parameter type list</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.parameter_type_listImpl#getParameter_lista <em>Parameter lista</em>}</li>
 * </ul>
 *
 * @generated
 */
public class parameter_type_listImpl extends MinimalEObjectImpl.Container implements parameter_type_list
{
  /**
   * The cached value of the '{@link #getParameter_lista() <em>Parameter lista</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameter_lista()
   * @generated
   * @ordered
   */
  protected parameter_lista parameter_lista;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected parameter_type_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PARAMETER_TYPE_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public parameter_lista getParameter_lista()
  {
    return parameter_lista;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParameter_lista(parameter_lista newParameter_lista, NotificationChain msgs)
  {
    parameter_lista oldParameter_lista = parameter_lista;
    parameter_lista = newParameter_lista;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA, oldParameter_lista, newParameter_lista);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParameter_lista(parameter_lista newParameter_lista)
  {
    if (newParameter_lista != parameter_lista)
    {
      NotificationChain msgs = null;
      if (parameter_lista != null)
        msgs = ((InternalEObject)parameter_lista).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA, null, msgs);
      if (newParameter_lista != null)
        msgs = ((InternalEObject)newParameter_lista).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA, null, msgs);
      msgs = basicSetParameter_lista(newParameter_lista, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA, newParameter_lista, newParameter_lista));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA:
        return basicSetParameter_lista(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA:
        return getParameter_lista();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA:
        setParameter_lista((parameter_lista)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA:
        setParameter_lista((parameter_lista)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PARAMETER_TYPE_LIST__PARAMETER_LISTA:
        return parameter_lista != null;
    }
    return super.eIsSet(featureID);
  }

} //parameter_type_listImpl
