/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>additive expression linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression_linha#getAdditive_expression_complement <em>Additive expression complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression_linha#getAdditive_expression_linha <em>Additive expression linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_linha()
 * @model
 * @generated
 */
public interface additive_expression_linha extends EObject
{
  /**
   * Returns the value of the '<em><b>Additive expression complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Additive expression complement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additive expression complement</em>' containment reference.
   * @see #setAdditive_expression_complement(additive_expression_complement)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_linha_Additive_expression_complement()
   * @model containment="true"
   * @generated
   */
  additive_expression_complement getAdditive_expression_complement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression_linha#getAdditive_expression_complement <em>Additive expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additive expression complement</em>' containment reference.
   * @see #getAdditive_expression_complement()
   * @generated
   */
  void setAdditive_expression_complement(additive_expression_complement value);

  /**
   * Returns the value of the '<em><b>Additive expression linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Additive expression linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additive expression linha</em>' containment reference.
   * @see #setAdditive_expression_linha(additive_expression_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_linha_Additive_expression_linha()
   * @model containment="true"
   * @generated
   */
  additive_expression_linha getAdditive_expression_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression_linha#getAdditive_expression_linha <em>Additive expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additive expression linha</em>' containment reference.
   * @see #getAdditive_expression_linha()
   * @generated
   */
  void setAdditive_expression_linha(additive_expression_linha value);

} // additive_expression_linha
