/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>cast expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.cast_expression#getUnary_expression <em>Unary expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.cast_expression#getType_name <em>Type name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.cast_expression#getCast_expression <em>Cast expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getcast_expression()
 * @model
 * @generated
 */
public interface cast_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Unary expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary expression</em>' containment reference.
   * @see #setUnary_expression(unary_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getcast_expression_Unary_expression()
   * @model containment="true"
   * @generated
   */
  unary_expression getUnary_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.cast_expression#getUnary_expression <em>Unary expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary expression</em>' containment reference.
   * @see #getUnary_expression()
   * @generated
   */
  void setUnary_expression(unary_expression value);

  /**
   * Returns the value of the '<em><b>Type name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type name</em>' containment reference.
   * @see #setType_name(type_name)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getcast_expression_Type_name()
   * @model containment="true"
   * @generated
   */
  type_name getType_name();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.cast_expression#getType_name <em>Type name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type name</em>' containment reference.
   * @see #getType_name()
   * @generated
   */
  void setType_name(type_name value);

  /**
   * Returns the value of the '<em><b>Cast expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cast expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cast expression</em>' containment reference.
   * @see #setCast_expression(cast_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getcast_expression_Cast_expression()
   * @model containment="true"
   * @generated
   */
  cast_expression getCast_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.cast_expression#getCast_expression <em>Cast expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cast expression</em>' containment reference.
   * @see #getCast_expression()
   * @generated
   */
  void setCast_expression(cast_expression value);

} // cast_expression
