/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DeclarationListLinhaAction#getDeclaration <em>Declaration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.DeclarationListLinhaAction#getDeclaration_list_linha <em>Declaration list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeclarationListLinhaAction()
 * @model
 * @generated
 */
public interface DeclarationListLinhaAction extends declaration_list_linha
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(declaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeclarationListLinhaAction_Declaration()
   * @model containment="true"
   * @generated
   */
  declaration getDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DeclarationListLinhaAction#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(declaration value);

  /**
   * Returns the value of the '<em><b>Declaration list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration list linha</em>' containment reference.
   * @see #setDeclaration_list_linha(declaration_list_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getDeclarationListLinhaAction_Declaration_list_linha()
   * @model containment="true"
   * @generated
   */
  declaration_list_linha getDeclaration_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.DeclarationListLinhaAction#getDeclaration_list_linha <em>Declaration list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration list linha</em>' containment reference.
   * @see #getDeclaration_list_linha()
   * @generated
   */
  void setDeclaration_list_linha(declaration_list_linha value);

} // DeclarationListLinhaAction
