/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declaration#getDeclaration_specifiers <em>Declaration specifiers</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declaration#getInit_declarator_list <em>Init declarator list</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declaration#getStatic_assert_declaration <em>Static assert declaration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration()
 * @model
 * @generated
 */
public interface declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration specifiers</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.declaration_specifiers}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration specifiers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration specifiers</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration_Declaration_specifiers()
   * @model containment="true"
   * @generated
   */
  EList<declaration_specifiers> getDeclaration_specifiers();

  /**
   * Returns the value of the '<em><b>Init declarator list</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.init_declarator_list}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init declarator list</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init declarator list</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration_Init_declarator_list()
   * @model containment="true"
   * @generated
   */
  EList<init_declarator_list> getInit_declarator_list();

  /**
   * Returns the value of the '<em><b>Static assert declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Static assert declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Static assert declaration</em>' containment reference.
   * @see #setStatic_assert_declaration(static_assert_declaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclaration_Static_assert_declaration()
   * @model containment="true"
   * @generated
   */
  static_assert_declaration getStatic_assert_declaration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.declaration#getStatic_assert_declaration <em>Static assert declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Static assert declaration</em>' containment reference.
   * @see #getStatic_assert_declaration()
   * @generated
   */
  void setStatic_assert_declaration(static_assert_declaration value);

} // declaration
