/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>external declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.external_declaration#getFunction_definitio <em>Function definitio</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.external_declaration#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getexternal_declaration()
 * @model
 * @generated
 */
public interface external_declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Function definitio</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function definitio</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function definitio</em>' containment reference.
   * @see #setFunction_definitio(function_definition)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getexternal_declaration_Function_definitio()
   * @model containment="true"
   * @generated
   */
  function_definition getFunction_definitio();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.external_declaration#getFunction_definitio <em>Function definitio</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function definitio</em>' containment reference.
   * @see #getFunction_definitio()
   * @generated
   */
  void setFunction_definitio(function_definition value);

  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(declaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getexternal_declaration_Declaration()
   * @model containment="true"
   * @generated
   */
  declaration getDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.external_declaration#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(declaration value);

} // external_declaration
