/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Identifier List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IdentifierListLinhaAction#getIdentifier <em>Identifier</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IdentifierListLinhaAction#getIdentifier_list_linha <em>Identifier list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIdentifierListLinhaAction()
 * @model
 * @generated
 */
public interface IdentifierListLinhaAction extends identifier_list_linha
{
  /**
   * Returns the value of the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier</em>' attribute.
   * @see #setIdentifier(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIdentifierListLinhaAction_Identifier()
   * @model
   * @generated
   */
  String getIdentifier();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IdentifierListLinhaAction#getIdentifier <em>Identifier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier</em>' attribute.
   * @see #getIdentifier()
   * @generated
   */
  void setIdentifier(String value);

  /**
   * Returns the value of the '<em><b>Identifier list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Identifier list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifier list linha</em>' containment reference.
   * @see #setIdentifier_list_linha(identifier_list_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIdentifierListLinhaAction_Identifier_list_linha()
   * @model containment="true"
   * @generated
   */
  identifier_list_linha getIdentifier_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IdentifierListLinhaAction#getIdentifier_list_linha <em>Identifier list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifier list linha</em>' containment reference.
   * @see #getIdentifier_list_linha()
   * @generated
   */
  void setIdentifier_list_linha(identifier_list_linha value);

} // IdentifierListLinhaAction
