/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Init Decclarator List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InitDecclaratorListLinhaAction#getInit_declarator <em>Init declarator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InitDecclaratorListLinhaAction#getInit_declarator_list_linha <em>Init declarator list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInitDecclaratorListLinhaAction()
 * @model
 * @generated
 */
public interface InitDecclaratorListLinhaAction extends init_declarator_list_linha
{
  /**
   * Returns the value of the '<em><b>Init declarator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init declarator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init declarator</em>' containment reference.
   * @see #setInit_declarator(init_declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInitDecclaratorListLinhaAction_Init_declarator()
   * @model containment="true"
   * @generated
   */
  init_declarator getInit_declarator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InitDecclaratorListLinhaAction#getInit_declarator <em>Init declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init declarator</em>' containment reference.
   * @see #getInit_declarator()
   * @generated
   */
  void setInit_declarator(init_declarator value);

  /**
   * Returns the value of the '<em><b>Init declarator list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init declarator list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init declarator list linha</em>' containment reference.
   * @see #setInit_declarator_list_linha(init_declarator_list_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInitDecclaratorListLinhaAction_Init_declarator_list_linha()
   * @model containment="true"
   * @generated
   */
  init_declarator_list_linha getInit_declarator_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InitDecclaratorListLinhaAction#getInit_declarator_list_linha <em>Init declarator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init declarator list linha</em>' containment reference.
   * @see #getInit_declarator_list_linha()
   * @generated
   */
  void setInit_declarator_list_linha(init_declarator_list_linha value);

} // InitDecclaratorListLinhaAction
