/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initializer List Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InitializerListLinhaAction#getInitializer_list_complement <em>Initializer list complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.InitializerListLinhaAction#getInit_declarator_list_linha <em>Init declarator list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInitializerListLinhaAction()
 * @model
 * @generated
 */
public interface InitializerListLinhaAction extends initializer_list_linha
{
  /**
   * Returns the value of the '<em><b>Initializer list complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initializer list complement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initializer list complement</em>' containment reference.
   * @see #setInitializer_list_complement(initializer_list_complement)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInitializerListLinhaAction_Initializer_list_complement()
   * @model containment="true"
   * @generated
   */
  initializer_list_complement getInitializer_list_complement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InitializerListLinhaAction#getInitializer_list_complement <em>Initializer list complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initializer list complement</em>' containment reference.
   * @see #getInitializer_list_complement()
   * @generated
   */
  void setInitializer_list_complement(initializer_list_complement value);

  /**
   * Returns the value of the '<em><b>Init declarator list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init declarator list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init declarator list linha</em>' containment reference.
   * @see #setInit_declarator_list_linha(init_declarator_list_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInitializerListLinhaAction_Init_declarator_list_linha()
   * @model containment="true"
   * @generated
   */
  init_declarator_list_linha getInit_declarator_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.InitializerListLinhaAction#getInit_declarator_list_linha <em>Init declarator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init declarator list linha</em>' containment reference.
   * @see #getInit_declarator_list_linha()
   * @generated
   */
  void setInit_declarator_list_linha(init_declarator_list_linha value);

} // InitializerListLinhaAction
