/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>multiplicative expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.multiplicative_expression#getCast_expression <em>Cast expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.multiplicative_expression#getMultiplicative_expression_linha <em>Multiplicative expression linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getmultiplicative_expression()
 * @model
 * @generated
 */
public interface multiplicative_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Cast expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cast expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cast expression</em>' containment reference.
   * @see #setCast_expression(cast_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getmultiplicative_expression_Cast_expression()
   * @model containment="true"
   * @generated
   */
  cast_expression getCast_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.multiplicative_expression#getCast_expression <em>Cast expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cast expression</em>' containment reference.
   * @see #getCast_expression()
   * @generated
   */
  void setCast_expression(cast_expression value);

  /**
   * Returns the value of the '<em><b>Multiplicative expression linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiplicative expression linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicative expression linha</em>' containment reference.
   * @see #setMultiplicative_expression_linha(multiplicative_expression_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getmultiplicative_expression_Multiplicative_expression_linha()
   * @model containment="true"
   * @generated
   */
  multiplicative_expression_linha getMultiplicative_expression_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.multiplicative_expression#getMultiplicative_expression_linha <em>Multiplicative expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicative expression linha</em>' containment reference.
   * @see #getMultiplicative_expression_linha()
   * @generated
   */
  void setMultiplicative_expression_linha(multiplicative_expression_linha value);

} // multiplicative_expression
