/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Post Fix Empry Params</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPostFixEmpryParams()
 * @model
 * @generated
 */
public interface PostFixEmpryParams extends postfix_expression_complement
{
} // PostFixEmpryParams
