/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Postfix Expression Linha Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PostfixExpressionLinhaAction#getPostfix_expression_complement <em>Postfix expression complement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PostfixExpressionLinhaAction#getPostfix_expression_linha <em>Postfix expression linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPostfixExpressionLinhaAction()
 * @model
 * @generated
 */
public interface PostfixExpressionLinhaAction extends postfix_expression_linha
{
  /**
   * Returns the value of the '<em><b>Postfix expression complement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postfix expression complement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postfix expression complement</em>' containment reference.
   * @see #setPostfix_expression_complement(postfix_expression_complement)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPostfixExpressionLinhaAction_Postfix_expression_complement()
   * @model containment="true"
   * @generated
   */
  postfix_expression_complement getPostfix_expression_complement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PostfixExpressionLinhaAction#getPostfix_expression_complement <em>Postfix expression complement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Postfix expression complement</em>' containment reference.
   * @see #getPostfix_expression_complement()
   * @generated
   */
  void setPostfix_expression_complement(postfix_expression_complement value);

  /**
   * Returns the value of the '<em><b>Postfix expression linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postfix expression linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postfix expression linha</em>' containment reference.
   * @see #setPostfix_expression_linha(postfix_expression_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPostfixExpressionLinhaAction_Postfix_expression_linha()
   * @model containment="true"
   * @generated
   */
  postfix_expression_linha getPostfix_expression_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PostfixExpressionLinhaAction#getPostfix_expression_linha <em>Postfix expression linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Postfix expression linha</em>' containment reference.
   * @see #getPostfix_expression_linha()
   * @generated
   */
  void setPostfix_expression_linha(postfix_expression_linha value);

} // PostfixExpressionLinhaAction
