/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>specifier qualifier list</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.specifier_qualifier_list#getType_specifier <em>Type specifier</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.specifier_qualifier_list#getSpecifier_qualifier_list <em>Specifier qualifier list</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.specifier_qualifier_list#getType_qualifier <em>Type qualifier</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getspecifier_qualifier_list()
 * @model
 * @generated
 */
public interface specifier_qualifier_list extends EObject
{
  /**
   * Returns the value of the '<em><b>Type specifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type specifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type specifier</em>' containment reference.
   * @see #setType_specifier(type_specifier)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getspecifier_qualifier_list_Type_specifier()
   * @model containment="true"
   * @generated
   */
  type_specifier getType_specifier();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.specifier_qualifier_list#getType_specifier <em>Type specifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type specifier</em>' containment reference.
   * @see #getType_specifier()
   * @generated
   */
  void setType_specifier(type_specifier value);

  /**
   * Returns the value of the '<em><b>Specifier qualifier list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Specifier qualifier list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specifier qualifier list</em>' containment reference.
   * @see #setSpecifier_qualifier_list(specifier_qualifier_list)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getspecifier_qualifier_list_Specifier_qualifier_list()
   * @model containment="true"
   * @generated
   */
  specifier_qualifier_list getSpecifier_qualifier_list();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.specifier_qualifier_list#getSpecifier_qualifier_list <em>Specifier qualifier list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Specifier qualifier list</em>' containment reference.
   * @see #getSpecifier_qualifier_list()
   * @generated
   */
  void setSpecifier_qualifier_list(specifier_qualifier_list value);

  /**
   * Returns the value of the '<em><b>Type qualifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type qualifier</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type qualifier</em>' containment reference.
   * @see #setType_qualifier(type_qualifier)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getspecifier_qualifier_list_Type_qualifier()
   * @model containment="true"
   * @generated
   */
  type_qualifier getType_qualifier();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.specifier_qualifier_list#getType_qualifier <em>Type qualifier</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type qualifier</em>' containment reference.
   * @see #getType_qualifier()
   * @generated
   */
  void setType_qualifier(type_qualifier value);

} // specifier_qualifier_list
