/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>struct declarator list</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.struct_declarator_list#getStruct_declarator <em>Struct declarator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.struct_declarator_list#getStruct_declarator_list_linha <em>Struct declarator list linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstruct_declarator_list()
 * @model
 * @generated
 */
public interface struct_declarator_list extends EObject
{
  /**
   * Returns the value of the '<em><b>Struct declarator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Struct declarator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Struct declarator</em>' containment reference.
   * @see #setStruct_declarator(struct_declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstruct_declarator_list_Struct_declarator()
   * @model containment="true"
   * @generated
   */
  struct_declarator getStruct_declarator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.struct_declarator_list#getStruct_declarator <em>Struct declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Struct declarator</em>' containment reference.
   * @see #getStruct_declarator()
   * @generated
   */
  void setStruct_declarator(struct_declarator value);

  /**
   * Returns the value of the '<em><b>Struct declarator list linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Struct declarator list linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Struct declarator list linha</em>' containment reference.
   * @see #setStruct_declarator_list_linha(struct_declarator_list_linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstruct_declarator_list_Struct_declarator_list_linha()
   * @model containment="true"
   * @generated
   */
  struct_declarator_list_linha getStruct_declarator_list_linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.struct_declarator_list#getStruct_declarator_list_linha <em>Struct declarator list linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Struct declarator list linha</em>' containment reference.
   * @see #getStruct_declarator_list_linha()
   * @generated
   */
  void setStruct_declarator_list_linha(struct_declarator_list_linha value);

} // struct_declarator_list
